### ISSUE TITLE
New filter for rhsm_log

### ISSUE THREAD

**Issue by TripleJQK** [RedHatInsights/insights-frontend-assets#17]
https://github.com/RedHatInsights/insights-plugins/pull/763
ERROR_MSG = "virt.host_type=hyperv, virt.uuid=Not Settable"
add_filter(Specs.rhsm_log, ERROR_MSG)
RhsmLog.keep_scan('uuid_break', ERROR_MSG)

**Comment by kylape** [comment]
Resolved in ed215800

**Comment by xiangce** [comment]
Thanks.

@TripleJQK - would you please take a look and close this issue? (we do not have the permission to close it.)
