### ISSUE TITLE
Update specs for openstack logs and configurations

### ISSUE THREAD

**Issue by chenlizhong** [RedHatInsights/insights-frontend-assets#19]
https://github.com/RedHatInsights/insights-core/pull/1087

From OSP 12, it is containerized. The log and configurations are different with previous release.

**Comment by kylape** [comment]
I think `heat_engine_log`, `keystone_log`, `heat_api_log` and`glance_api_log` should each be excluded from uploader.json until there are filters for each of them.

**Comment by kylape** [comment]
Resolved in c8e822a and 67f73e6.
