### ISSUE TITLE
Filter changes: Specs.journal_since_boot

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-frontend-assets#26]
https://github.com/RedHatInsights/insights-plugins/pull/774
~~~
INCIDENT = 'sshd: no hostkeys available -- exiting'
add_filter(Specs.journal_since_boot, 'ovirt-vmconsole-host-sshd')
~~~

**Comment by kylape** [comment]
Resolved in 6e7592df

**Comment by xiangce** [comment]
Hey @kylape, I cannot found the filter-pattern `ovirt-vmconsole-host-sshd` for Specs.journal_since_boot in this commit, did you miss it?

**Comment by kylape** [comment]
Can you please merge the plugin PR?  We will automatically include the filter after it's merged.
