### ISSUE TITLE
Filter Changes: Specs.gnocchi_metricd_log

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-frontend-assets#27]
https://github.com/RedHatInsights/insights-plugins/pull/779
~~~
add_filter(Specs.gnocchi_metricd_log, "ToozError: Cannot extend an unlocked lock")
~~~

**Comment by kylape** [comment]
Resolved in 22764677

**Comment by xiangce** [comment]
Is this duplicated? https://github.com/RedHatInsights/insights-frontend-assets/commit/22764677d4679c177eb78ca8535412338dc34e3a#diff-fc36584e56db2c0cb530cb47e0b27eceR959

**Comment by xiangce** [comment]
This one is duplicated with #21, close it.
