### ISSUE TITLE
New spec: neutron_l3_agent_log

### ISSUE THREAD

**Issue by xiangce** [RedHatInsights/insights-frontend-assets#29]
https://github.com/RedHatInsights/insights-core/pull/1108
~~~
neutron_l3_agent_log = simple_file("/var/log/neutron/l3-agent.log")
~~~

**Comment by kylape** [comment]
This is left on hold until filters are added for this log file.

**Comment by xiangce** [comment]
See https://github.com/RedHatInsights/insights-frontend-assets/pull/72
