### ISSUE TITLE
Add filter for Specs.mariadb_log in plugin

### ISSUE THREAD

**Issue by JoySnow** [RedHatInsights/insights-frontend-assets#9]
https://github.com/RedHatInsights/insights-plugins/pull/713

INCIDENT = 'OpenSSL internal error, assertion failed: Digest MD5 forbidden in FIPS mode!'
add_filter(Specs.mariadb_log, INCIDENT)

**Comment by kylape** [comment]
Fixed in ed215800

**Comment by xiangce** [comment]
Thanks.

@JoySnow - would you please to take a look and close this issue?

**Comment by JoySnow** [comment]
Thanks for @kylape  and @xiangce , I can close this issue here.
